name: CI Docker + PHPUnit

on:
  push:
    branches:
      - '**'    # ou change selon ta branche principale

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest #lancement sur une VM Ubuntu

    services:
      docker:
        image: docker:20.10.16 #déclare un service Docker pour s’assurer que Docker est ok dans l’environnement -optionnel
        options: --privileged #pour avoir les droits - optionnel

    steps:
      - name: Checkout repository #copie du code dans la VM
        uses: actions/checkout@v4

      - name: Set up Docker Compose #lancement des dockers
        run: |
          docker-compose -f docker-compose.yml up -d --build 

      #tests phpunit ne se lancent que quand la BDD MySQL est OK, on ping pour vérifier que sql répond
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mysql8-Cube mysqladmin ping -h "localhost" --silent; do 
            sleep 2
          done

      - name: Install dependencies with Composer
        run: |
          docker exec php82-Cube bash -c "cd /var/www/project && composer install"

      - name: Run PHPUnit tests in PHP container #lancement des tests PHP UNit si BDD OK
        run: |
          docker exec php82-Cube bash -c "cd /var/www/project && ./vendor/bin/phpunit"

      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.yml down
