version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_REPO: https://github.com/PipouTeam/CUBE-CESI.git
        GITHUB_BRANCH: ${GITHUB_BRANCH:-main}
    container_name: php82-Cube
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql8-Cube
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo 
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-Cube
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
