version: '3.8'

services:
  php:
    image: php:8.2-apache
    ports:
      - 8002:80
    volumes:
      - ../.:/var/www/project
      - ../public:/var/www/html
    build:
      context: .
      dockerfile: DockerFile
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: vide-grenier 
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - 3302:3306
    volumes:
      - mysql-data-stage:/var/lib/mysql
      - ../sql/prod:/docker-entrypoint-initdb.d
  phpma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
    ports:
      - 8802:80
volumes:
  mysql-data-stage: