name: CI Docker + PHPUnit

on:
  push:
    branches:
      - 92-create-ci-pipeline-with-github-actions

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose -f vide-grenier-en-ligne-master/docker/local/docker-compose.dev.yml up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec mysql8-Cube mysqladmin ping -h "localhost" --silent; do 
            sleep 2
          done

      - name: Run PHPUnit tests in PHP container
        run: |
          docker exec php82-Cube bash -c "cd /var/www/project && ./vendor/phpunit"

      - name: Shut down Docker Compose
        run: |
          docker compose -f vide-grenier-en-ligne-master/docker/local/docker-compose.dev.yml down
