name: Containers checking

on:
  push:
    branches:
      - dev

jobs:
  check-docker-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker containers
        run: |
          cd vide-grenier-en-ligne-master
          ./scripts/dev_docker_env_start.sh

      - name: Check Docker containers
        run: docker ps

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready (timeout: 120s)..."
          timeout=120
          while ! docker exec dev-db-1 mysqladmin ping -h "localhost" --silent; do
            sleep 2
            timeout=$((timeout - 2))
            if [ $timeout -le 0 ]; then
              echo "MySQL did not become ready in time."
              exit 1
            fi
          done
          echo "MySQL is ready."

      - name: Wait for PHP container to be ready
        run: |
          echo "Waiting for PHP container to be ready (timeout: 120s)..."
          timeout=120
          while ! docker exec dev-php-1 php -v > /dev/null 2>&1; do
            sleep 2
            timeout=$((timeout - 2))
            if [ $timeout -le 0 ]; then
              echo "PHP container did not become ready in time."
              exit 1
            fi
          done
          echo "PHP container is ready."

      - name: Wait for phpMyAdmin container to be ready
        run: |
          echo "Waiting for phpMyAdmin container to be ready (timeout: 120s)..."
          timeout=120
          while ! docker exec dev-phpma-1 ps aux | grep -q 'apache2'; do
            sleep 2
            timeout=$((timeout - 2))
            if [ $timeout -le 0 ]; then
              echo "phpMyAdmin container did not become ready in time."
              exit 1
            fi
          done
          echo "phpMyAdmin container is ready."

      - name: List running containers
        run: docker ps

      - name: Shut down Docker containers
        run: |
          cd vide-grenier-en-ligne-master
          ./scripts/all_down.sh
