name: PHPUnit tests

on:
  push:
    branches:
      - "**"

jobs:
  run-phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit tests/
          echo "Adios"
